### ISSUE TITLE
Issue for less days in start date that counted end date

### ISSUE THREAD

**Issue by 1MaJKeL1** [ProJSLib/jsbits#1]
Hi,
I've checked this lib and I noticed that is counting incorrectly in case:
less days on start day than calculated 
![image](https://user-images.githubusercontent.com/30533643/186677182-17a49fc6-7bd2-40a1-b968-c48f28d108f0.png)

**Comment by aMarCruz** [comment]
Hi @1MaJKeL1 ,
the result is as expected, according to how this library was designed.

If you want to get the end of the month, you need to add logic for it with an additional function.
Closing, thanks for your interest.
